const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Клавиатура: 0},
	{Тач: 0},
	{СледитьЗа: 0},
	{"8Направлений": 0},
	{hero: 0},
	{Время: 0},
	{Твёрдый: 0},
	{verityCoinsBlock: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{ChatGPTImage30Июн2026Г11_55_: 0},
	{bg: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Поворот: 0},
	{verityCoins: 0},
	{Якорь: 0},
	{Текст: 0},
	{Текст2: 0},
	{labirintBlock: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Спрайт7: 0},
	{вфыввыф: 0},
	{Спрайт11: 0},
	{Спрайт10: 0},
	{tilemap_black_packed: 0},
	{ТайловыйФон: 0},
	{"3DФигуры": 0},
	{blockbutton: 0},
	{Текст3: 0},
	{ТайловыйФон2: 0},
	{openbuttommutton: 0},
	{openveritycoins: 0},
	{Текст4: 0},
	{AllCoins: 0},
	{Coins: 0}
];

self.InstanceType = {
	Клавиатура: class extends self.IInstance {},
	Тач: class extends self.IInstance {},
	hero: class extends self.ISpriteInstance {},
	verityCoinsBlock: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	ChatGPTImage30Июн2026Г11_55_: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	verityCoins: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Текст2: class extends self.ITextInstance {},
	labirintBlock: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	вфыввыф: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	tilemap_black_packed: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	_3DФигуры: class extends self.I3DShapeInstance {},
	blockbutton: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	openbuttommutton: class extends self.ISpriteInstance {},
	openveritycoins: class extends self.ISpriteInstance {},
	Текст4: class extends self.ITextInstance {}
}